#!/bin/bash

echo "# begin build properties"
echo "# autogenerated by buildinfo.sh"

echo "ro.build.id=$BUILD_ID"
echo "android.os.Build.ID=$BUILD_ID"
echo "ro.build.display.id=$BUILD_DISPLAY_ID"
echo "ro.build.version.incremental=$BUILD_NUMBER"
echo "android.os.Build.VERSION.INCREMENTAL=$BUILD_NUMBER"
echo "ro.build.version.sdk=$PLATFORM_SDK_VERSION"
echo "android.os.Build.VERSION.SDK=$PLATFORM_SDK_VERSION"
echo "ro.build.version.codename=$PLATFORM_VERSION_CODENAME"
echo "ro.build.version.release=$PLATFORM_VERSION"
echo "android.os.Build.VERSION.RELEASE=$PLATFORM_VERSION"
echo "ro.build.date=`date`"
echo "ro.build.date.utc=`date +%s`"
echo "ro.build.type=$TARGET_BUILD_TYPE"
echo "ro.build.user=$USER"
echo "ro.build.host=`hostname`"
echo "ro.build.tags=$BUILD_VERSION_TAGS"
#begin mod by ysten
if [ -n "$PRODUCT_MANUFACTURER_YS" ] ; then
  echo "ro.product.model=$PRODUCT_MODEL_YS"
  echo "android.os.Build.MODEL=$PRODUCT_MODEL_YS"
else
  echo "ro.product.model=$PRODUCT_MODEL"
  echo "android.os.Build.MODEL=$PRODUCT_MODEL"
fi
#end mod by ysten
echo "ro.product.brand=$PRODUCT_BRAND"
echo "android.os.Build.BRAND=$PRODUCT_BRAND"
echo "ro.product.name=$PRODUCT_NAME"
echo "ro.product.device=$TARGET_DEVICE"
echo "ro.product.board=$TARGET_BOOTLOADER_BOARD_NAME"
echo "android.os.Build.BOARD=$TARGET_BOOTLOADER_BOARD_NAME"
echo "ro.product.cpu.abi=$TARGET_CPU_ABI"
if [ -n "$TARGET_CPU_ABI2" ] ; then
  echo "ro.product.cpu.abi2=$TARGET_CPU_ABI2"
fi
#begin mod by ysten
if [ -n "$PRODUCT_MANUFACTURER_YS" ] ; then
  echo "ro.product.manufacturer=$PRODUCT_MANUFACTURER_YS"
  echo "android.os.Build.MANUFACTURER=$PRODUCT_MANUFACTURER_YS"
else
  echo "ro.product.manufacturer=$PRODUCT_MANUFACTURER"
  echo "android.os.Build.MANUFACTURER=$PRODUCT_MANUFACTURER"
fi
#end mod by ysten
if [ -n "$PRODUCT_DEFAULT_LANGUAGE" ] ; then
  echo "ro.product.locale.language=$PRODUCT_DEFAULT_LANGUAGE"
fi
if [ -n "$PRODUCT_DEFAULT_REGION" ] ; then
  echo "ro.product.locale.region=$PRODUCT_DEFAULT_REGION"
fi
echo "ro.wifi.channels=$PRODUCT_DEFAULT_WIFI_CHANNELS"
echo "ro.board.platform=$TARGET_BOARD_PLATFORM"

echo "# ro.build.product is obsolete; use ro.product.device"
echo "ro.build.product=$TARGET_DEVICE"

echo "# Do not try to parse ro.build.description or .fingerprint"
echo "ro.build.description=$PRIVATE_BUILD_DESC"
echo "ro.build.fingerprint=$BUILD_FINGERPRINT"
echo "android.os.Build.FINGERPRINT=CPU:4cores2GHz/GPU:5cores750MHz/RAM:1G/FLASH:8G"
echo "ro.build.characteristics=$TARGET_AAPT_CHARACTERISTICS"

echo "# end build properties"
